### ISSUE TITLE
I need Docker Joomla image of version 2.15.4

### ISSUE THREAD

**Issue by mdfareed2001** [joomla-docker/docker-joomla#132]
Hi,

In Docker hub, there are no images for Joomla old versions less than 3.10.4
I need Docker Joomla image of version 2.15.4 
Kindly help.

Regards,
Mohammed Fareed
md_fareed2001@yahoo.co.in

**Comment by Hackwar** [comment]
The oldest Docker image we have is with Joomla 3.4. We don't have any images for Joomla 2.5.

**Comment by mdfareed2001** [comment]
Thanks for quick reply. I have installed Joomla using Docker image. Do you have any idea,  how to downgrade Joomla to any older version or how to downgrade the php version of Joomla?

**Comment by Llewellynvdm** [comment]
There is an unofficial way for you to get that kind of image.
Fork this repo, then in your fork open the https://github.com/joomla-docker/docker-joomla/blob/master/versions.json file and add the version details you would like to build.

Then run https://github.com/joomla-docker/docker-joomla/blob/master/update.sh in your repository.

This should build the Docker files for that version. Do note that you may need to tweak that docker file a little more since its aimed at Joomla 3.4 and above... then do a normal docker build on the docker file and you will have a local image.

This image will not get any support or other help from the official maintainers... but it will give you an image.

Also note that the lowest I have taken Joomla was 3.4 as @Hackwar stated. [Here is where I play with Joomla and Docker](https://github.com/octoleo/docker-joomla)...
