### ISSUE TITLE
How to upgrade Joomla?

### ISSUE THREAD

**Issue by bzisl** [joomla-docker/docker-joomla#146]
I've tried upgrade the docker image (docker-compose pull && docker-compose down && docker-compose up -d) and also upgrade from there admin dashboard without any success.
Could you explain and document how to upgrade a Joomla dockerized site?
Sorry for my lack of knowledge here.

**Comment by Llewellynvdm** [comment]
The docker images do not have a upgrade path at this time. But since the underlining container in which Joomla runs are compatible you should be able to upgrade via the Joomla Administrator area as you would do on any other normal instance of Joomla.

Should your upgrade in the **admin dashboard** fail it is normally not because of the Joomla "dockerized" container, but usually because of other third party extensions. This because all our test and migration paths are being tested in "dockerized" containers and they do work.

So using docker to upgrade will fail, and is highly discouraged. You should only use the **admin dashboard**, unless you find that your container is very outdated, in which case we recommend a migration to a container with the same major version before using the **admin dashboard** to upgrade to the next major version.

You must understand that the **admin dashboard** upgrade path is the recommend upgrade path.

I assume that if you are running a Joomla "dockerized" container, you are also having a persistent database and filesystem. Do backup those before attempting any upgrade.

Here is how I would upgrade a Joomla 3 website.

> The following assumes you have persistent database and filesystem.

- Take down the Joomla 3 container
- Backup all the data and files
- Delete the last **Joomla 3 image** from my docker instance.
- Pull up your Joomla 3 container again
- Done

This will give you the newer container but with all your old files and data. This is also how you could try out higher versions of PHP if you want to test your system in those versions.

Yet stepping from Joomla 3 to Joomla 4 the steps will be as follow:

> The following assumes you have persistent database and filesystem.

- Make sure you are on the newest container (for Joomla 3) with the PHP 7.4
- Then make backups of all your data and files
- Start a copy of your container (so you can fail without effecting your live system).
- Using the **admin dashboard** upgrade to Joomla 4.x (check the upgrade notices if there are any)
- When the upgrade was successful test all your 3rd party extensions **
- Should an extension fail contact the extension developers for help.

Then if all works as expected you **now** have the option to upgrade the container to the Joomla 4 container, and the steps will be as follow:

> The following assumes you have persistent database and filesystem.

- Take down the Joomla 3 container
- Backup all the data and files (just to be safe)
- Change your composer file to target Joomla 4 image
- Pull up your container again, using the Joomla 4 image
- Done

This is by no means documentation, but should be enough to achieve a successful upgrade.

** should your upgrade still fail and that not because of 3rd party extensions, then please [open an issue here](https://github.com/joomla/joomla-cms/issues?q=is%3Aissue+is%3Aopen+upgrade) with all the needed details.
