### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by webchun** [joomla-docker/docker-joomla#15]
When I enabled/mounted the volume, the Joomla performance is decreasing significantly. Any clue?

**Comment by mbabker** [comment]
Not having a functional Docker installation anymore to work with, my first guess would be that there's added latency with filesystem operations since the volume is now on a remote system in relation to the Docker container.

**Comment by webchun** [comment]
I found that there are many discussions about this subject and looks like it still not resolved yet for years. Some discussion said this only happened when they have a large number of files, so maybe providing separated volume to mount can become a solution? Maybe dividing /var/www/html into several parts such as /var/www/html/components,/var/www/html/modules,/var/www/html/plugin,/var/www/html/templates

**Comment by mbabker** [comment]
Except by doing that, the files at the application root become stored outside of a mountable volume (index.php, .htaccess, robots.txt primarily).  And keeping a volume at that level makes having volumes for each directory a pointless option IMO.

Even if the volume is split into several smaller volumes, it's still in essence accessing a network drive versus a local drive, so that alone isn't making a major improvement.

The other thing that would most likely affect performance is the database connection.  Since a MySQL server isn't compiled directly into this container (it's only a web server), the database connection therefore too makes network requests to a remote server versus more conventional hosting platforms where the `*AMP` stack is an all-in-one package.

**Comment by webchun** [comment]
> The other thing that would most likely affect performance is the database connection. Since a MySQL server isn't compiled directly into this container (it's only a web server), the database connection therefore too makes network requests to a remote server versus more conventional hosting platforms where the *AMP stack is an all-in-one package.

I don't think embedded MySQL would add significant impact/performance improvements, as when I tested it, using an external MySQL container was already giving a good performance. The problem comes only when volume is mounted/enabled. 

But I think to have mysql compiled directly into the container would be a good idea, especially for getting more adopters. There is an all-in-one unofficial wordpress package available [here](https://hub.docker.com/r/tlongren/docker-wordpress-nginx-ssh/) that is really easy to install (no external db container to setup, no additional step to perform, you can install it by one click of Kitematic). Maybe you will be interested to [fork it](https://github.com/tlongren/docker-wordpress-nginx-ssh)? I tried to fork it before but it was failed to build when I tried to update the php version to 7.

**Comment by Llewellynvdm** [comment]
this is so old, I will close it... should any of you feel it needs more attention, please open a new issue taking all revisions to these images into account.
