### ISSUE TITLE
data image

### ISSUE THREAD

**Issue by pollen8** [joomla-docker/docker-joomla#2]
would it be possible to install the joomla files into a mounted volume? that way we can work on the Joomla code from the host machine

**Comment by mbabker** [comment]
It should be possible using Docker's configuration routines.  The image structure is based on the WordPress image, so I would think that the guide at http://www.sitepoint.com/how-to-use-the-official-docker-wordpress-image/ (which has a section talking about volume mapping) should apply here too without any adjustment to the Dockerfile.

**Comment by RedsAnDev** [comment]
Should be possible to update actually image? Exspecially to test new features!!!

**Comment by jsivak** [comment]
I've got the same question as @RedsAnDev, how would I go about upgrading to a new release of Joomla with this docker image when I have mounted the /var/www/html to a directory on the host system?

In reading the Dockerfile, the contents of /var/www/html are only copied over if the files don't exist. When Joomla 3.7.5 or 3.8 comes out, its not clear how I would get the fixes / updates of that image to "overwrite" my current hosted directory contents.

Thanks

**Comment by mbabker** [comment]
For now you'd just update Joomla as you would a normal web hosted install.  I would suggest that it might be too complicated to try and not make the entire `/var/www/html` directory a volume because of the nature of Joomla and how updates need to be performed with specific logic in mind (just replacing the files without performing the extra steps run in the install routine can be harmful to your site).

So it should be safe to update the image to update the outside dependencies (`*AMP` server stack) without messing up your actual Joomla site.

**Comment by jsivak** [comment]
Understood. Was "hoping" that the Docker image would be able to "manage" more of the upgrade rather than going thru the Joomla Web upgrade steps via the website.

No worries though.. I've not been let down by the Joomla upgrade processes yet.. ;)

**Comment by Llewellynvdm** [comment]
Well, I know this is a very old thread, and I assume all have moved on.

Mounting any thing into a Docker container is normal and easy these days... let me know if anything still remains unclear directly related to the current Joomla Docker image.
