### ISSUE TITLE
Add support for Docker secrets

### ISSUE THREAD

**Issue by sytabaresa** [joomla-docker/docker-joomla#24]
Hello, many official docker images have support to Docker Secrets, this image could have an enviroment variable JOOMLA_DB_PASSWORD_FILE that uses this characteristic for better security and deploy strategies.

**Comment by bweston92** [comment]
Hi @sytabaresa I totally agree, want to provide a PR?

Here is a good example https://github.com/docker-library/rabbitmq/blob/master/3.6/debian/docker-entrypoint.sh#L8

**Comment by mbabker** [comment]
Like I said in another issue I plan on catching up with some of the stuff they've done in the WordPress Docker image (since this one is so closely modeled off of it), and that would seem to include support for secrets.

So, even if a PR doesn't get done (though I'd greatly appreciate it if one were, I don't exactly have a functional Docker environment anymore which is why this image has mostly just been syncing up with new Joomla releases), I do intend on getting support for it in before the Joomla 3.8 release goes out.
