### ISSUE TITLE
Joomla docker commit and restart

### ISSUE THREAD

**Issue by thisistheredteam** [joomla-docker/docker-joomla#92]
hello people! 
Hope your having a great day working from home.

I'm currently done building my joomla docker container. 
What i'm trying to do is commit it to a new image and launch it from the new image without too much configuration..

However when my mqsql container was ready I launched my commited image by entering :
`docker run --name joomlacool --link mysql:db -e JOOMLA_DB_HOST=db:3306 -e JOOMLA_DB_USER=joomla -e JOOMLA_DB_PASSWORD=redacted -p 80:80 -d joomlacool `

Joomla worked fine but sadly I had to redo the initial installation of Joomla..
also my plugins were not there anymore.
Other data included in the filesystem like user files where still present.

So i'm looking to re-run the container how I left it when I commited the image.

Thanks in advance

**Comment by Llewellynvdm** [comment]
Sorry for the delayed reply here...

The way official images work, we add the release zip file into the image, and add a hash to the image that validates this file has not changed and so doing add the needed security to the image as to be expected.

So your approach will not work... the best option you have is to clone this repository, change the Docker build scripts, build your own image from the ground-up and inevitably break all needed security protocol. But since it is for your own use... this should be okay.

The other option you have is to add a auto-install script to the container.... but yes it requires enough BASH scripting knowledge and will not be-easy to achieve.

What I can tell you is that I already played around with many of these ideas, when we deployed a [pizza-bugs-and-fun](https://github.com/Llewellynvdm/Joomla-Docker-Fun/blob/main/JOOMLA4.0.0-beta5/docker-entrypoint.sh#L86) testing server array of servers. 

The current containers also has the option to add your own package URL... so if you forked it and updated the [versions-helper.json](https://github.com/joomla-docker/docker-joomla/blob/master/versions-helper.json) with your Joomla package, where you have your own version of Joomla ready to deploy with your database and other needed stuff like those distributed by Yootheme.. .you can do that.

[Here I did the with a RC I wanted to these](https://github.com/octoleo/docker-joomla/tree/118a6b459d5eca541e555e53362c57822b624089) look at the [versions-helper.json](https://github.com/octoleo/docker-joomla/blob/118a6b459d5eca541e555e53362c57822b624089/versions-helper.json) you will see that version has a extra value called `package` and that will then be used as the package added to the image, when you build the image.

There some more details... would you be interested on more info let me know, and I will make a short tutorial how all this works.

For now I will close this issue... but your welcome to let me know if you need any further help.
